CREATE DATABASE tp08
WITH TEMPLATE = template0
ENCODING = 'UTF8'
LOCALE_PROVIDER = libc
LOCALE = 'Spanish_Argentina.1252';



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.provinces (
    id integer NOT NULL,
    name text NOT NULL,
    full_name text,
    latitude double precision,
    longitude double precision,
    display_order integer
);

ALTER TABLE public.provinces OWNER TO postgres;

ALTER TABLE public.provinces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.newtable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO public.provinces VALUES (1, 'Buenos Aires', 'Provincia de Buenos Aires', -34.9215, -57.9545, 1);
INSERT INTO public.provinces VALUES (2, 'Córdoba', 'Provincia de Córdoba', -31.4201, -64.1888, 2);
INSERT INTO public.provinces VALUES (3, 'Santa Fe', 'Provincia de Santa Fe', -31.6333, -60.7, 3);
INSERT INTO public.provinces VALUES (4, 'Mendoza', 'Provincia de Mendoza', -32.8895, -68.8458, 4);
INSERT INTO public.provinces VALUES (5, 'Tucumán', 'Provincia de Tucumán', -26.8083, -65.2176, 5);
INSERT INTO public.provinces VALUES (6, 'Salta', 'Provincia de Salta', -24.7859, -65.4117, 6);
INSERT INTO public.provinces VALUES (7, 'Neuquén', 'Provincia del Neuquén', -38.9516, -68.0591, 7);

SELECT pg_catalog.setval('public.newtable_id_seq', 7, true);

ALTER TABLE ONLY public.provinces
    ADD CONSTRAINT newtable_pk PRIMARY KEY (id);